### ISSUE TITLE
Missing / hard-coded dependencies

### ISSUE THREAD

**Issue by carlo-fiorina** [DLR-RY/ECI4FOAM#2]
First of all, let me say that this is a great project. Thanks a lot for publishing it. It is going to be useful for a lot of people.

This issue is just to let the developers know that some hard-coded   dependencies have remained into:

ECI4FOAM/src/embeddingPython/Make/options
and
ECI4FOAM/src/externalComm/Make/options

In particular, absolute library paths are included for python3.9, pybind and a few other libraries (see the result of the "grep -ir henning" command that I have run in the folder FMU4FOAM).

This will make the installation fail for other users.

---

grep -ir henning
ECI4FOAM/src/embeddingPython/Make/options:-I/media/henning/ssd1linux/miniconda3/envs/py39/include/python3.9 \ 
ECI4FOAM/src/embeddingPython/Make/options:-I/media/henning/ssd1linux/miniconda3/envs/py39/include/python3.9
ECI4FOAM/src/embeddingPython/Make/options:-L/media/henning/ssd1linux/miniconda3/envs/py39/lib/python3.9/config-3.9-x86_64-linux-gnu \ 
ECI4FOAM/src/embeddingPython/Make/options:-L/media/henning/ssd1linux/miniconda3/envs/py39/lib \ 
ECI4FOAM/src/embeddingPython/Make/options:-Wl,-rpath=/media/henning/ssd1linux/miniconda3/envs/py39/lib \ 
ECI4FOAM/src/embeddingPython/Make/options:   -I/home/henning/.conan/data/pybind11/2.7.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/pybind11 \
ECI4FOAM/src/embeddingPython/Make/options:   -I/home/henning/.conan/data/pybind11/2.7.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include
ECI4FOAM/src/embeddingPython/Make/options:   -L/home/henning/.conan/data/pybind11/2.7.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib 
ECI4FOAM/src/embeddingPython/Make/options.template:-I/media/henning/ssd1linux/miniconda3/envs/py39/include/python3.9 \ 
ECI4FOAM/src/embeddingPython/Make/options.template:-I/media/henning/ssd1linux/miniconda3/envs/py39/include/python3.9
ECI4FOAM/src/embeddingPython/Make/options.template:-L/media/henning/ssd1linux/miniconda3/envs/py39/lib/python3.9/config-3.9-x86_64-linux-gnu \ 
ECI4FOAM/src/embeddingPython/Make/options.template:-L/media/henning/ssd1linux/miniconda3/envs/py39/lib \ 
ECI4FOAM/src/embeddingPython/Make/options.template:-Wl,-rpath=/media/henning/ssd1linux/miniconda3/envs/py39/lib \ 
ECI4FOAM/src/embeddingPython/pyInterp.H:    Henning Scheufler, DLR, all rights reserved.
ECI4FOAM/src/externalComm/Make/options:       -I/home/henning/.conan/data/cppzmq/4.7.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include \
ECI4FOAM/src/externalComm/Make/options:   -I/home/henning/.conan/data/nlohmann_json/3.9.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include \
ECI4FOAM/src/externalComm/Make/options:   -I/home/henning/.conan/data/zeromq/4.3.4/_/_/package/4a4500bdf9b12024d2cf6e38334aa40f7cabc37c/include \
ECI4FOAM/src/externalComm/Make/options:   -I/home/henning/.conan/data/libsodium/1.0.18/_/_/package/090017fccd7b493020671020e5964801d6ba8054/include
ECI4FOAM/src/externalComm/Make/options:       -L/home/henning/.conan/data/cppzmq/4.7.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib \ 
ECI4FOAM/src/externalComm/Make/options:   -L/home/henning/.conan/data/zeromq/4.3.4/_/_/package/4a4500bdf9b12024d2cf6e38334aa40f7cabc37c/lib \ 
ECI4FOAM/src/externalComm/Make/options:   -L/home/henning/.conan/data/libsodium/1.0.18/_/_/package/090017fccd7b493020671020e5964801d6ba8054/lib \

**Comment by HenningScheufler** [comment]
Thanks for bringing this up!

The options file in the make folder should be overwritten with the dependency of the conan package manager (see allwmake). If you are coming from fmu4foam please check if conan is successfully installed. The requirement of conan needs to be stated in the readme

**Comment by carlo-fiorina** [comment]
I see. Thanks for clarifying. Since we are on the subject of updating the readme, please notice that the package does not compile on Python 3.10. It's a known problem related to mutablemapping, which in 3.10 is imported from collections.abc instead of simply collections

**Comment by carlo-fiorina** [comment]
My bad. Apparently I was missing ANACONDA. Maybe another requirement to be mentioned in the README file?
On the other hand, I am still stuck in the installation. You can see the error snippet below, with the full compilation log attached.
Is there a specifc version of boost that is needed?

g++ -std=c++14 -m64 -pthread -DOPENFOAM=2112 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -Wno-unknown-pragmas  -O3  -DNoRepository -ftemplate-depth-100 -I/usr/lib/openfoam/openfoam2112/src/finiteVolume/lnInclude -I/usr/lib/openfoam/openfoam2112/src/meshTools/lnInclude -I/usr/lib/openfoam/openfoam2112/src/dynamicMesh/lnInclude -I/usr/lib/openfoam/openfoam2112/src/rigidBodyDynamics/lnInclude -I/usr/lib/openfoam/openfoam2112/src/functionObjects/field/lnInclude -I/usr/lib/openfoam/openfoam2112/src/functionObjects/forces/lnInclude 
-I/usr/lib/openfoam/openfoam2112/src/TurbulenceModels/turbulenceModels/lnInclude -I/usr/lib/openfoam/openfoam2112/src/TurbulenceModels/compressible/lnInclude -I/home/carlo/.conan/data/cppzmq/4.7.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/carlo/.conan/data/nlohmann_json/3.9.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -I/home/carlo/.conan/data/zeromq/4.3.4/_/_/package/29f9b88b7d31710de5168e78f04b101f9a1be822/include -I/home/carlo/.conan/data/libsodium/1.0.18/_/_/package/91a02ef095d6f8a3742bd7f4ddf9b748d82a004c/include -iquote. -IlnInclude -I/usr/lib/openfoam/openfoam2112/src/OpenFOAM/lnInclude -I/usr/lib/openfoam/openfoam2112/src/OSspecific/POSIX/lnInclude   -fPIC -c networkInterface/socket.C -o Make/linux64GccDPInt32Opt/networkInterface/socket.o
In file included from networkInterface/socket.C:20:0:
networkInterface/socket.H:64:10: error: ‘io_context’ in namespace ‘net’ does not name a type
     net::io_context ioc_;
          ^~~~~~~~~~
networkInterface/socket.C: In constructor ‘Foam::socket::socket(const Foam::dictionary&)’:
networkInterface/socket.C:35:5: error: class ‘Foam::socket’ does not have any field named ‘ioc_’
     ioc_(),
     ^~~~
networkInterface/socket.C:36:15: error: ‘ioc_’ was not declared in this scope
     resolver_(ioc_),
               ^~~~
networkInterface/socket.C:36:15: note: suggested alternative: ‘sock_’
     resolver_(ioc_),
               ^~~~
               sock_
/usr/lib/openfoam/openfoam2112/wmake/rules/General/transform:34: recipe for target 'Make/linux64GccDPInt32Opt/networkInterface/socket.o' failed
make: *** [Make/linux64GccDPInt32Opt/networkInterface/socket.o] Error 1

[compError.txt](https://github.com/DLR-RY/ECI4FOAM/files/9460849/compError.txt)

**Comment by HenningScheufler** [comment]
Thanks for reporting the bug. There were multiple bugs in the CI. The continue-on-error flag falsely labelled the test as passing but they were not. The socket.H is no longer compiled as boost is a quite a heavy dependency and zmq is much simpler to use. 

Anaconda should not be required to install the library. Only pip needs to be configured properly.

The library should work with python 3.10.

PS: The conan integration with OpenFOAM significantly simplifies the installation process of external libraries

**Comment by HenningScheufler** [comment]
The issue should be fixed please checkout the newest version of FMU4FOAM.

**Comment by carlo-fiorina** [comment]
Great, thanks!
I'll check asap

**Comment by carlo-fiorina** [comment]
Hi again.

This is just to report that I have a student who tried installing from scratch.
He had only one issue:
"liblapack.so.3 cannot open shared object file no such file or directory"
which he solved by installing the library (using CONDA)

I believe there is also a problem of compatibility with OpenFOAM 2206, but I need to check better. In case, I'll open a separate issue, and hopefully help out solving it
